org.gradle.jvmargs=-Xmx5120m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.workers.max=4
org.gradle.vfs.watch=false
org.gradle.daemon=false
android.enableR8.fullMode=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
kapt.use.worker.api=true
