name: Generate Keystore

on: [workflow_dispatch]

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Verify Java Installation
        run: |
          java -version
          which keytool
          $JAVA_HOME/bin/keytool -help
      
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore appduct-release.keystore \
            -alias appduct \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass 3|Ft-c&2Q2Rh \
            -keypass 3|Ft-c&2Q2Rh \
            -dname "CN=Appduct,OU=Engineering,O=Appduct,L=Port Harcourt,ST=Rivers,C=NG"
      
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: appduct-release-keystore
          path: appduct-release.keystore
